# ------------------------------------------------------------------------------------
# 기본 설정 (Hugo 자체 설정)
# ------------------------------------------------------------------------------------

# 웹사이트의 기본 URL입니다. Github Pages 배포 시 "https://<username>.github.io/" 형식으로 설정합니다.
baseURL = "https://quartzs2.github.io/"

# 사이트 언어 설정입니다. (한국어)
languageCode = "ko"

# 웹사이트의 전체 제목입니다. 브라우저 탭 등에 표시됩니다.
title = "quartzs2의 blog"

# 사용할 Hugo 테마의 이름입니다.
theme = "PaperMod"

# 검색 엔진이 사이트를 크롤링할 수 있도록 robots.txt 파일을 생성할지 여부입니다.
enableRobotsTXT = true

# 빌드 시 초안(draft) 상태의 게시물을 포함할지 여부입니다. (false: 포함 안 함)
buildDrafts = false

# 빌드 시 예약 발행(미래 날짜) 게시물을 포함할지 여부입니다. (false: 포함 안 함)
buildFuture = false

# 빌드 시 만료된 게시물을 포함할지 여부입니다. (false: 포함 안 함)
buildExpired = false

# Google Analytics 추적 ID입니다. (GA4 측정 ID 형식: "G-XXXXXXXXXX")
# 프로덕션에서만 스크립트가 삽입됩니다. (hugo.IsProduction 함수 사용)
# HTML에 gtag 스니펫을 직접 넣었다면 제거하여 중복 집계를 방지하세요.
googleAnalytics = "G-03B7GYGYJC"

# 코드 블록 하이라이팅에 Pygments CSS 클래스를 사용할지 여부입니다.
pygmentsUseClasses = true

# ------------------------------------------------------------------------------------
# 페이지네이션 설정
# ------------------------------------------------------------------------------------
[pagination]
# 목록 페이지(예: 게시글 목록)에서 한 페이지에 보여줄 게시물 개수입니다.
pagerSize = 5


# ------------------------------------------------------------------------------------
# Minify 설정 (파일 압축)
# ------------------------------------------------------------------------------------
[minify]
# XML 파일 압축을 비활성화할지 여부입니다.
disableXML = true

# 최종 출력물(HTML 등)을 압축하여 파일 크기를 줄일지 여부입니다.
minifyOutput = true


# ------------------------------------------------------------------------------------
# 테마 파라미터 설정 (PaperMod 테마 전용 설정)
# ------------------------------------------------------------------------------------
[params]
# 웹사이트의 환경을 지정합니다. (예: "development", "production")
# env = "production"  # Hugo의 hugo.IsProduction 함수를 사용하여 자동으로 판별

# 웹사이트 제목입니다. params 내의 title은 주로 SEO나 테마 내에서 사용됩니다.
title = "quartzs2의 blog"

# 웹사이트에 대한 설명입니다. 검색 엔진 결과(SEO)에 표시됩니다.
description = "앱같은 웹을 만드는걸 좋아하는, quartzs2의 블로그입니다."

# 웹사이트의 주요 키워드입니다. SEO에 사용됩니다.
keywords = [ "Blog", "Portfolio", "PaperMod" ]

# 기본 작성자 이름입니다.
author = "Me"

# 소셜 미디어 공유 시 사용될 기본 이미지 경로입니다. (Open Graph, Twitter Cards)
images = [ "<link or path of image for opengraph, twitter-cards>" ]

# 날짜 표시 형식입니다. (Go 언어의 날짜 형식 규칙을 따름: "January 2, 2006")
DateFormat = "2006년 1월 2일"

# 기본 테마 설정입니다. 'auto'는 방문자의 시스템 설정을 따릅니다. ('light', 'dark'로 고정 가능)
defaultTheme = "auto"

# 라이트/다크 모드 전환 토글 버튼을 숨길지 여부입니다. (false: 표시)
disableThemeToggle = false

# 게시물 상단에 예상 읽기 시간을 표시할지 여부입니다.
ShowReadingTime = true

# 게시물 하단에 공유 버튼을 표시할지 여부입니다.
ShowShareButtons = true

# 게시물 하단에 이전/다음 게시물 링크를 표시할지 여부입니다.
ShowPostNavLinks = true
mainSections = ["posts"]

# 페이지 상단에 현재 위치 경로(Breadcrumbs)를 표시할지 여부입니다.
ShowBreadCrumbs = true

# 코드 블록에 '복사' 버튼을 표시할지 여부입니다.
ShowCodeCopyButtons = true

# 게시물 상단에 단어 수를 표시할지 여부입니다.
ShowWordCount = true

# 카테고리/태그 목록 페이지에 RSS 버튼을 표시할지 여부입니다.
ShowRssButtonInSectionTermList = false

# Hugo 자체의 목차(Table of Contents) 기능을 사용할지 여부입니다.
UseHugoToc = true

# 목록 페이지의 첫 번째 게시물을 특별한 스타일로 강조하는 기능을 비활성화할지 여부입니다.
disableSpecial1stPost = false

# 화면 우측 하단에 '맨 위로 가기' 버튼을 숨길지 여부입니다. (false: 표시)
disableScrollToTop = false

# 댓글 기능을 사용할지 여부입니다. (true로 설정 시 추가 구성 필요)
comments = true

# 게시물의 메타 정보(날짜, 읽기 시간 등)를 숨길지 여부입니다.
hidemeta = false

# 목록 페이지에서 게시물 요약을 숨길지 여부입니다.
hideSummary = false

# 게시물 페이지에서 목차를 표시할지 여부입니다.
showtoc = false

# 게시물 페이지에서 목차를 기본적으로 펼쳐진 상태로 둘지 여부입니다.
tocopen = false


# --- Assets (파비콘 등) 설정 ---
[params.assets]
# 파비콘 이미지 경로입니다.
favicon = "<link / abs url>"
favicon16x16 = "<link / abs url>"
favicon32x32 = "<link / abs url>"
apple_touch_icon = "<link / abs url>"
safari_pinned_tab = "<link / abs url>"


# --- 로고/사이트 이름 설정 ---
[params.label]
# 헤더 좌측 상단에 표시될 텍스트입니다.
text = "quartzs2의 blog"

# 텍스트 앞에 표시될 아이콘 이미지 경로입니다.
icon = "/apple-touch-icon.png"

# 아이콘의 높이입니다.
iconHeight = 35


# --- 프로필 모드 설정 (홈페이지 스타일) ---
[params.profileMode]
# 프로필 모드를 활성화할지 여부입니다. (true: 활성화, false: 일반 목록 스타일)
enabled = false

# 프로필 모드에서 표시될 제목입니다.
title = "ExampleSite"

# 프로필 모드에서 표시될 부제입니다.
subtitle = "This is subtitle"

# 프로필 이미지 경로입니다.
imageUrl = "<img location>"

# 프로필 이미지 너비입니다.
imageWidth = 120

# 프로필 이미지 높이입니다.
imageHeight = 120

# 프로필 이미지에 대한 설명(alt text)입니다.
imageTitle = "my image"


# 프로필 모드에서 표시될 버튼들입니다.
[[params.profileMode.buttons]]
# 버튼에 표시될 텍스트입니다.
name = "Posts"
# 버튼 클릭 시 이동할 URL입니다.
url = "posts"

[[params.profileMode.buttons]]
name = "Tags"
url = "tags"


# --- 일반 홈페이지 정보 설정 (프로필 모드 비활성화 시) ---
[params.homeInfoParams]
# 홈페이지에 표시될 큰 제목입니다.
Title = "앱같은 웹을 만드는 걸 좋아하는 프론트엔드 개발자 천승현입니다 👋"

# 제목 아래에 표시될 내용입니다.
Content = "email: csh001231@gmail.com"


# --- 소셜 아이콘 링크 설정 ---
# [[params.socialIcons]]
# name = "twitter"
# url = "https://twitter.com/"

# [[params.socialIcons]]
# name = "stackoverflow"
# url = "https://stackoverflow.com"

[[params.socialIcons]]
# 아이콘 이름입니다. (테마에서 지원하는 아이콘 이름 사용)
name = "github"
# 연결할 URL 주소입니다.
url = "https://github.com/quartzs2"


[params.utterances]
repo = "quartzs2/github-blog-comments"
issueTerm = "pathname"
theme = "preferred-color-scheme"


# --- 검색 엔진 사이트 인증 설정 (주석 처리됨) ---
# [params.analytics.google]
# SiteVerificationTag = "XYZabc"

# [params.analytics.bing]
# SiteVerificationTag = "XYZabc"

# [params.analytics.yandex]
# SiteVerificationTag = "XYZabc"


# --- 게시물 커버 이미지 설정 (주석 처리됨) ---
# [params.cover]
# hidden = true # 모든 곳에서 커버 이미지 숨기기
# hiddenInList = true # 목록 페이지에서 커버 이미지 숨기기
# hiddenInSingle = true # 개별 게시물 페이지에서 커버 이미지 숨기기


# --- 검색 기능(Fuse.js) 설정 (주석 처리됨) ---
[params.fuseOpts]
isCaseSensitive = false # 대소문자 구분 여부
shouldSort = true # 검색 결과 정렬 여부
location = 0
distance = 1000
threshold = 0.4 # 검색 정확도 (0.0: 완전 일치, 1.0: 모든 결과)
minMatchCharLength = 1
keys = [ "title", "permalink", "summary", "content" ] # 검색 대상 필드
limit = 30


# ------------------------------------------------------------------------------------
# 메뉴 설정
# ------------------------------------------------------------------------------------

# 메인 메뉴에 표시될 항목을 정의합니다.
[[menu.main]]
# 메뉴 항목의 고유 식별자입니다.
identifier = "search"
# 메뉴에 표시될 이름입니다.
name = "검색"
# 클릭 시 이동할 URL입니다.
url = "/search/"
# 메뉴 항목의 순서입니다. 숫자가 작을수록 앞에 배치됩니다.
weight = 5

[[menu.main]]
identifier = "categories"
name = "카테고리"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "archive"
name = "아카이브"
url = "/archive/"
weight = 15

[[menu.main]]
identifier = "tags"
name = "태그"
url = "/tags/"
weight = 20


# ------------------------------------------------------------------------------------
# 마크다운 렌더링 설정
# ------------------------------------------------------------------------------------
[markup.highlight]
# 코드 하이라이팅에 CSS 클래스를 사용하도록 설정합니다. (false 권장)
noClasses = false


# ------------------------------------------------------------------------------------
# 캐시 설정
# ------------------------------------------------------------------------------------
[caches]
  # 이미지 처리 관련 캐시 설정입니다.
  [caches.images]
    # 캐시된 이미지가 저장될 디렉토리입니다.
    dir = ':cacheDir/images'


# ------------------------------------------------------------------------------------
# 출력 포맷 설정
# ------------------------------------------------------------------------------------
[outputs]
home = ["HTML", "RSS", "JSON"]


